name: ci

on: [push, pull_request]

jobs:
  build:
    name: Build and test

    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      
    - name: Get cmake
      uses: lukka/get-cmake@latest

    - name: Install OpenEXR (Ubuntu)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: sudo apt-get -y install libopenexr-dev

    - name: Install OpenEXR (MacOS)
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install openexr

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ..
      
    - name: Build
      run: cmake --build build --parallel
      
    - name: Test
      run: ./pbrt_test
      working-directory: build
